language: python

cache: pip

python:
- '3.5'
- '3.6'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install: true

script: true

deploy:
  provider: pypi
  user: stegben
  password:
    secure: "DTSRNOiF/LAx3csLHdt1xyzsCbqz+mShy61OpXr37RSyhmyj9N1ZSRoxby6X1pfsIim1PBku/yfe3kvlWHa+Kv1vTK6S84RvO5Y6d6hpwhg27Cc29Un81drbXni5KLmYl2oKH/T4yAoLus337+WCQugniiGnkje9L4M0i0AduDci6xA4USoPk2U8jrrU1mCxW8LJaQalW4aselN+0hK95xwRpDi4g+zY51l2zNtWE3pZyGd0kZs233TgqOQVFzJ4pzRlQMKnzRi9j+089vW9DCNamiLmTnKY92jZLUAv090RNUDL+HMiZ1Ca3bxi7iOYjAhXxjW3rZWNgFtZZyTGuds9anc8t/Ov/0zBGXorHxQPyC7rZpkVPZqvT8ql1Zl8Sao3kWwWPp+DrCvwGONe6tUC/hu4H9c2/WeVxyMYWD26sYNzSwxl/NdleKfl1j5kqmeSO3Y3mzqQP5p86KFP8UorCKsOU+AYm3YJjPGL7DD5TNyCjs1a5jm0Ss/psEW+Ny2/Bcu7xnIHwyqEqLqH9CInqzARLbxArMUuEr/+I1fxqZgS+BU9BZSuKG+9z9FJ1rrogBFdOmWo0q1NIx/8SvBeIjuVvlyhP2w8DV6IlPNgcwJwnKuUvWtemA/h4Wg8VNoKUGM+HJmH1M+bVzY5hkUvBcWeaRdJUMNyJAed+tk="
  distributions: sdist bdist_wheel
  on:
    tags: true
